### ISSUE TITLE
kind of import error I am getting when I am running it

### ISSUE THREAD

**Issue by Yash7689** [webtorrent/webtorrent-cli#221] opened 2022-01-17 08:35 UTC
/usr/local/lib/node_modules/webtorrent-cli/bin/cmd.js:2
import chalk from 'chalk'
       ^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by alxhotel** [comment] 2022-01-17 14:44
Duplicate of #208

**Closed by alxhotel** 2022-01-17 14:44 UTC
