### ISSUE TITLE
Can't Use..."webtorrent --help" shows error.

### ISSUE THREAD

**Issue by whitedevil-glitch** [webtorrent/webtorrent-cli#216] opened 2022-01-05 12:30 UTC
**What version of this package are you using?**
latest

**What operating system, Node.js, and npm version?**
6.14.4

**What happened?**
whenever I type "webtorrent --help" it shows error.
 
**What did you expect to happen?**
expected to show the commands which i can use.

**Are you willing to submit a pull request to fix this bug?**
yes. if necessary

![gnome-shell-screenshot-54RSF1](https://user-images.githubusercontent.com/73755149/148217884-b37a3a8d-c381-469e-8b78-07cbbfbed008.png)

**Comment by alxhotel** [comment] 2022-01-05 14:51
Duplicate of #212

**Closed by alxhotel** 2022-01-05 14:51 UTC
