### ISSUE TITLE
?

### ISSUE THREAD

**Issue by HORUS405** [webtorrent/webtorrent-cli#171] opened 2021-07-06 23:54 UTC
UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 3.3.0, webtorrent 1.1.0, node v12.21.0, linux x64, exit 1
/home/horus/Desktop/Projects/Projects/Hydra-405/webtorrent-cli/node_modules/utp-native/lib/connection.js:197
  binding.utp_napi_connect(this._utp._handle, this._handle, port, ip)
          ^

Error: invalid argument
    at Connection._connect (/home/horus/Desktop/Projects/Projects/Hydra-405/webtorrent-cli/node_modules/utp-native/lib/connection.js:197:11)
    at /home/horus/Desktop/Projects/Projects/Hydra-405/webtorrent-cli/node_modules/utp-native/lib/connection.js:189:10
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'EINVAL'
}

**Comment by alxhotel** [comment] 2021-07-06 23:56
Duplicate of https://github.com/webtorrent/webtorrent/issues/2128

**Closed by alxhotel** 2021-07-06 23:56 UTC
