### ISSUE TITLE
Using quite alot memory, says "Possible EventEmitter memory leak detected"

### ISSUE THREAD

**Issue by slrslr** [webtorrent/webtorrent-cli#55] opened 2018-01-10 09:01 UTC
Hello,

it is around 2 weeks i am trying to seed a torrent using webtorrent-cli

> webtorrent --keep-seeding --verbose seed "magnet:?xt=urn:btih:HashHere&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=wss%3A%2F%2Ftracker.webtorrent.io"

and it happened 2 times already that after a few days of the Webtorrent process runtime, it start using 90%+ memory on my 512MB RAM VPS.

Here is how RAM usage looks like when the process is running: https://snag.gy/lk6A1w.jpg

The process is running inside Linux "screen":

> root      6339  0.0  0.0  21920    96 ?        Ss    2017   0:00 SCREEN
root      6343  0.0  0.0  11444    64 pts/2    Ss    2017   0:00  \_ /bin/bash
root     20140  0.6 86.3 1814328 452588 pts/2  Sl+  Jan04  59:46      \_ WebTorrent

Also this is what appears as a result of webtorrent command runtime, during high memory usage:
(node:20140) Warning: Possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit

It may be problem that OpenVZ virtualization do not allocate guaranteed memory but shared memory resources, i do not know, but maybe Webtorrent-cli can be made so this issue can be prevented?

The OS is CentOS 6.9 64bit, 2.6.32-042stab125.3

**Comment by rien333** [comment] 2018-01-10 18:50
I think this is because webtorrent tries to keep most of the torrent/video data in memory. Unfortunately for me, this "bug"/feature affects me in such a way that it brings my system to a halt.

**Comment by jimmywarting** [comment] 2018-08-28 11:39
@slrslr if you didn't know this you can drop images directly into the text box instead of linking them to another service

↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

![skarmavbild 2018-08-28 kl 13 37 09](https://user-images.githubusercontent.com/1148376/44720583-87e5d380-aac7-11e8-8769-afa15ad034ca.png)

**Comment by feross** [comment] 2019-09-10 23:48
Duplicate of https://github.com/webtorrent/webtorrent/issues/1026

**Closed by feross** 2019-09-10 23:48 UTC
