### ISSUE TITLE
webtorrent process crashes on opening localhost in browser

### ISSUE THREAD

**Issue by evxn** [webtorrent/webtorrent-cli#135] opened 2020-04-26 18:50 UTC
**What version of this package are you using?**
webtorrent-cli 3.0.5, webtorrent 0.107.17

**What operating system, Node.js, and npm version?**
node v12.16.2, macOS Catalina 10.15.4

**What happened?**

During torrent download I typed `localhost:52977` in the browser's url bar, hit enter, then webtorrent process crashed. I could reproduce it easily 2 times. 

**Error in the terminal, where `webtorrent-cli` was running:**

```UNEXPECTED ERROR: If this is a bug in WebTorrent, report it!
OPEN AN ISSUE: https://github.com/webtorrent/webtorrent-cli/issues

DEBUG INFO: webtorrent-cli 3.0.5, webtorrent 0.107.17, node v12.16.2, darwin x64, exit 1
_http_outgoing.js:526
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:526:11)
    at Server.onRequest (/usr/local/Cellar/webtorrent-cli/3.0.5/libexec/lib/node_modules/webtorrent-cli/node_modules/webtorrent/lib/server.js:87:9)
    at Server.emit (events.js:322:22)
    at parserOnIncoming (_http_server.js:784:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Request from Chrome network tab copied as Node.js fetch:**

```
fetch("http://localhost:52977/", {
  "headers": {
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "accept-language": "en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "none",
    "sec-fetch-user": "?1",
    "upgrade-insecure-requests": "1"
  },
  "referrerPolicy": "no-referrer-when-downgrade",
  "body": null,
  "method": "GET",
  "mode": "cors"
});
```

**Same request as cURL:**
```
curl 'http://localhost:52977/' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Sec-Fetch-Site: none' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Accept-Language: en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7' \
  --compressed
```

**Comment by feross** [comment] 2020-11-19 05:43
I cannot reproduce this issue on the latest version of `webtorrent-cli` so I'm assuming that it's now fixed. If this is not the case, please leave a comment.

**Closed by feross** 2020-11-19 05:43 UTC
